spring.application.name=FE_voucher_management

spring.datasource.url=jdbc:mysql://localhost:3306/voucher_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true